version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./data.db:/app/data.db  # 🔥 Adicionado: persistência real do banco!
    environment:
      - API_URL=http://backend:8000

  dashboard:
    build:
      context: .  # 🔥 Já ajustado
      dockerfile: backend/dashboard/Dockerfile.dashboard
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./backend:/app/backend
    environment:
      - API_URL=http://backend:8000
